#!/bin/sh
# .gitconfigに設定したaliasをスペースを入れずに実行できるようにする
# `git al` みたいなのを `gal` で打てるようにする

import_gitconfig_alias() {
  local GITCONFIG_PATH="${HOME}/.gitconfig"
  local ALIAS_GITCOMMANDS=$(sed -ne '/^\[alias\]/,$p' ${GITCONFIG_PATH} | grep -v '\[alias\]' | awk '{print $1}')

  local command
  for command in ALIAS_GITCOMMANDS; do
    alias g${command}="git ${command}"
  done
}

import_gitconfig_alias
