#!/bin/sh

\ag -l '.css%3Fbody=1.css' | xargs \sed -i -e 's/.css%3Fbody=1.css/.css/g'
for filename in `ag -g '.css\?body=1.css'`; do mv $filename ${filename%%\?body=1.css}; done

\ag -l '.js%3Fbody=1' | xargs \sed -i -e 's/.js%3Fbody=1/.js/g'
for filename in `ag -g '.js\?body=1'`; do mv $filename ${filename%%\?body=1}; done
