#!/bin/sh

LS="ls -F --color --group-directories-first"

if [ "$#" = 0 ]; then
  $LS .
fi

for input in "$@"
do
  if [ -d "$input" ]; then
    $LS "$input"
  elif [ -f "$input" ]; then
    if [ -f /usr/share/vim/vim73/macros/less.sh ]; then
      /usr/share/vim/vim73/macros/less.sh "$input"
    elif [ -f /usr/share/vim/vim74/macros/less.sh ]; then
      /usr/share/vim/vim74/macros/less.sh "$input"
    else
      echo "less.sh not found"
    fi
  else
    echo "(´ ･ω ･｀)知らんがな"
  fi
done
