#!/bin/bash
#
# ファイルかディレクトリかを気にせずに表示できる
#
# show [ FILE | DIR ]

LS="ls -FG"

if [ "$#" = 0 ]; then
  $LS .
fi

for input in "$@"
do
  if [ -d "$input" ]; then
    $LS "$input"
  elif [ -f "$input" ]; then
    /usr/share/vim/vim73/macros/less.sh "$input"
  else
    echo "Sorry, i don't no ..."
  fi
done
