#!/bin/bash

rspec-git-diff() {
  local spec_files=`git diff --name-only | \grep '\_spec.rb$\|spec.*\.feature$' | ruby -pe "gsub(/\n/, ' ')"`
  [ -z "${spec_files}" ] && return 0;

  echo "${spec_files}"
  bundle exec rspec $@ ${spec_files}
}

rspec-git-diff $@
