#!/bin/bash
#
# ファイルかディレクトリかを気にせずに表示できる
#
# show [ FILE | DIR ]

if [ "$#" = 0 ]; then
  ls -F --color
fi

for input in "$@"
do
  if [ -d "$input" ]; then
    ls -F --color "$input"
  elif [ -f "$input" ]; then
    /usr/share/vim/vim73/macros/less.sh "$input"
  else
    echo "Sorry, i dont no ..."
  fi
done
