#!/bin/sh

LS="ls -F --color"

if [ "$#" = 0 ]; then
  $LS .
fi

for input in "$@"
do
  if [ -d "$input" ]; then
    $LS "$input"
  elif [ -f "$input" ]; then
    /usr/share/vim/vim73/macros/less.sh "$input"
  else
    echo "Sorry, i dont no ..."
  fi
done
