#!/bin/bash
#
# rmの代わりに使う。いわゆるゴミ箱。
#
# trash [ file...]

TRASH_DIR="$HOME/.Trash"

while getopts "csh" opts
do
  case $opts in
    c)
      rm -rf $TRASH_DIR/*
      echo "clear ${TRASH_DIR}"
      exit 0
      ;;
    s)
      ls -F --color $TRASH_DIR
      exit 0
      ;;
    h)
      echo "trash help"
      echo "-c : clear files in TRASH_DIR"
      echo "-s : show files in TRASH_DIR"
      exit 0
      ;;
  esac
done

mv "$@" "$TRASH_DIR"
